<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ddsclient</AssemblyName>
    <RootNamespace>DdsAmbassador.DDSClient.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DdsAmbassador.DDSClient\DdsAmbassador.DDSClient.csproj" />
  </ItemGroup>
</Project>
